### ISSUE TITLE
Request for information (htmltabs.sty)

### ISSUE THREAD

**Issue by vincentb1** [patrickschulz/patschouli#1]
Sorry for using this channel, but I found no alternartive to get in touch with you.
I am seeking information about the `htmltabs.sty` package mentioned here https://www.dante.de/veranstaltungen/dante2021/vortraege/#schulz .

Are you the author of this package, and is it possible to find some documentation / package repo ?

**Comment by patrickschulz** [comment]
Hi, 
no problem! Unfortunately, I can't help you as I'm not the author of this package nor the speaker in the mentioned presentation. I just happen to share the name ;)

**Comment by vincentb1** [comment]
Thank you for your kind feedback !
